run_name: mtl_nb_002
epochs: 10
batch_size: 64
lr: 0.0003
age_weight: 0.001
variant: large
# prepare_mtl_from_roboflow_emotion.py 실행 후 생성
train_csv: data/mtl/train.csv
val_csv: data/mtl/val.csv
data_root: data/mtl
